port: 7880
bind_addresses:
    - "0.0.0.0"
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 50200
    use_external_ip: true

keys:
    V_LIVEKIT_API_KEY: V_LIVEKIT_API_SECRET

logging:
    json: false
    level: info


