services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v3.6.5}
    container_name: edge-traefik
    restart: always
    ports:
      - "8444:443"
      - "8080:80"
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamics:/etc/traefik/dynamics
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/etc/traefik/acme.json
    environment:
      - DOCKER_API_VERSION=1.44
    networks:
      edge:
        ipv4_address: 10.0.0.2
        aliases:
          - traefik

networks:
  edge:
    external: true
