api:
  dashboard: true
  insecure: true

log:
  level: INFO


entryPoints:

  # ---------------------------------------------- HTTP
  web:
    address: ":80"
    # Redirection handled by Nginx, but we keep this entrypoint for ACME challenges.

  # ---------------------------------------------- HTTPS
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: le

  matrix:
    address: ":8448"
    http:
      tls:
        certResolver: le



certificatesResolvers:
  le:
    acme:
      email: V_EMAIL_ADDRESS
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: "edge"
  file:
    directory: /etc/traefik/dynamics
    watch: true

